version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "4000:27017"
    expose:
      - "27017"
    restart: always

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=bootstrapmicroservices
      - STORAGE_ACCESS_KEY=pTBcML6ggJ7EKaIS7VNX+6AeKwrzXXf6l3SXtSkj44jdWHWFpjkncUAYOCrjy1riMzkJYTrbeT9wKXPf5gNyEw==
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=4001
    restart: "no"
