version: '3'
services:

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4001:3000"
    environment:
      - IMAGE_STORAGE_ACCOUNT_NAME=bootstrapmicroservices
      - IMAGE_STORAGE_ACCESS_KEY=pTBcML6ggJ7EKaIS7VNX+6AeKwrzXXf6l3SXtSkj44jdWHWFpjkncUAYOCrjy1riMzkJYTrbeT9wKXPf5gNyEw==
    restart: always

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4002:3000"
    environment:
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=3000
    restart: always
